// Generated by scripts/generate-framework-registry.mts (ed4562009f3b). Do not edit.
import { tv } from "tailwind-variants";

export const componentContract = {
  "description": "Responsive application sidebar with controlled collapse state.",
  "name": "sidebar",
  "parts": [
    {
      "element": "div",
      "name": "SidebarProvider",
      "slot": "sidebar-wrapper"
    },
    {
      "element": "aside",
      "name": "Sidebar",
      "slot": "sidebar"
    },
    {
      "element": "button",
      "name": "SidebarTrigger",
      "slot": "sidebar-trigger"
    },
    {
      "element": "button",
      "name": "SidebarRail",
      "slot": "sidebar-rail"
    },
    {
      "element": "main",
      "name": "SidebarInset",
      "slot": "sidebar-inset"
    },
    {
      "element": "input",
      "name": "SidebarInput",
      "slot": "sidebar-input"
    },
    {
      "element": "div",
      "name": "SidebarHeader",
      "slot": "sidebar-header"
    },
    {
      "element": "div",
      "name": "SidebarFooter",
      "slot": "sidebar-footer"
    },
    {
      "element": "div",
      "name": "SidebarSeparator",
      "slot": "sidebar-separator"
    },
    {
      "element": "div",
      "name": "SidebarContent",
      "slot": "sidebar-content"
    },
    {
      "element": "div",
      "name": "SidebarGroup",
      "slot": "sidebar-group"
    },
    {
      "element": "div",
      "name": "SidebarGroupLabel",
      "slot": "sidebar-group-label"
    },
    {
      "element": "button",
      "name": "SidebarGroupAction",
      "slot": "sidebar-group-action"
    },
    {
      "element": "div",
      "name": "SidebarGroupContent",
      "slot": "sidebar-group-content"
    },
    {
      "element": "ul",
      "name": "SidebarMenu",
      "slot": "sidebar-menu"
    },
    {
      "element": "li",
      "name": "SidebarMenuItem",
      "slot": "sidebar-menu-item"
    },
    {
      "element": "button",
      "name": "SidebarMenuButton",
      "slot": "sidebar-menu-button"
    },
    {
      "element": "button",
      "name": "SidebarMenuAction",
      "slot": "sidebar-menu-action"
    },
    {
      "element": "div",
      "name": "SidebarMenuBadge",
      "slot": "sidebar-menu-badge"
    },
    {
      "element": "div",
      "name": "SidebarMenuSkeleton",
      "slot": "sidebar-menu-skeleton"
    },
    {
      "element": "ul",
      "name": "SidebarMenuSub",
      "slot": "sidebar-menu-sub"
    },
    {
      "element": "li",
      "name": "SidebarMenuSubItem",
      "slot": "sidebar-menu-sub-item"
    },
    {
      "element": "a",
      "name": "SidebarMenuSubButton",
      "slot": "sidebar-menu-sub-button"
    }
  ],
  "props": {
    "collapsible": {
      "defaultValue": "offcanvas",
      "description": "Choose how the desktop sidebar collapses.",
      "type": "SidebarCollapsible",
      "values": [
        "offcanvas",
        "icon",
        "none"
      ]
    },
    "defaultOpen": {
      "defaultValue": true,
      "description": "Set the initial uncontrolled desktop state.",
      "type": "boolean"
    },
    "isActive": {
      "defaultValue": false,
      "description": "Mark a menu action as the current destination.",
      "type": "boolean"
    },
    "placement": {
      "defaultValue": "left",
      "description": "Place the sidebar at the logical start or end.",
      "type": "SidebarPlacement",
      "values": [
        "left",
        "right"
      ]
    },
    "scrollFade": {
      "defaultValue": false,
      "description": "Add a fade treatment to overflowing navigation.",
      "type": "boolean"
    },
    "showIcon": {
      "defaultValue": false,
      "description": "Render an icon placeholder in menu skeletons.",
      "type": "boolean"
    },
    "showOnHover": {
      "defaultValue": false,
      "description": "Keep a menu action visible only around interaction.",
      "type": "boolean"
    },
    "variant": {
      "defaultValue": "sidebar",
      "description": "Select the shell treatment.",
      "type": "SidebarVariant",
      "values": [
        "sidebar",
        "floating",
        "inset"
      ]
    }
  },
  "scenarios": [
    {
      "assertions": [
        "supports controlled and uncontrolled desktop state",
        "persists desktop state for seven days",
        "toggles with mod+b"
      ],
      "name": "desktop-state"
    },
    {
      "assertions": [
        "uses an independent mobile open state",
        "closes the mobile surface through its binding"
      ],
      "name": "mobile-state"
    },
    {
      "assertions": [
        "preserves every public part and data-slot",
        "supports left and right placement",
        "keeps logical RTL layout classes"
      ],
      "name": "composition"
    }
  ],
  "strategy": "custom"
} as const;


