export interface ChartBlockManifestEntry {
  description: string;
  exportName: string;
  id: string;
  name: string;
  subcategory: string;
  subcategoryLabel: string;
}

/** shadcn/ui chart examples — order matches https://ui.shadcn.com/charts */
export const CHART_BLOCKS_MANIFEST: ChartBlockManifestEntry[] = [
  {
    id: "chart-area-interactive",
    subcategory: "area-charts",
    subcategoryLabel: "Area Charts",
    name: "Area Interactive",
    description: "An interactive area chart",
    exportName: "ChartAreaInteractive",
  },
  {
    id: "chart-area-default",
    subcategory: "area-charts",
    subcategoryLabel: "Area Charts",
    name: "Area Default",
    description: "A simple area chart",
    exportName: "ChartAreaDefault",
  },
  {
    id: "chart-area-linear",
    subcategory: "area-charts",
    subcategoryLabel: "Area Charts",
    name: "Area Linear",
    description: "A linear area chart",
    exportName: "ChartAreaLinear",
  },
  {
    id: "chart-area-step",
    subcategory: "area-charts",
    subcategoryLabel: "Area Charts",
    name: "Area Step",
    description: "A step area chart",
    exportName: "ChartAreaStep",
  },
  {
    id: "chart-area-legend",
    subcategory: "area-charts",
    subcategoryLabel: "Area Charts",
    name: "Area Legend",
    description: "An area chart with a legend",
    exportName: "ChartAreaLegend",
  },
  {
    id: "chart-area-stacked",
    subcategory: "area-charts",
    subcategoryLabel: "Area Charts",
    name: "Area Stacked",
    description: "A stacked area chart",
    exportName: "ChartAreaStacked",
  },
  {
    id: "chart-area-stacked-expand",
    subcategory: "area-charts",
    subcategoryLabel: "Area Charts",
    name: "Area Stacked Expand",
    description: "A stacked area chart with expand stacking",
    exportName: "ChartAreaStackedExpand",
  },
  {
    id: "chart-area-icons",
    subcategory: "area-charts",
    subcategoryLabel: "Area Charts",
    name: "Area Icons",
    description: "An area chart with icons",
    exportName: "ChartAreaIcons",
  },
  {
    id: "chart-area-gradient",
    subcategory: "area-charts",
    subcategoryLabel: "Area Charts",
    name: "Area Gradient",
    description: "An area chart with gradient fill",
    exportName: "ChartAreaGradient",
  },
  {
    id: "chart-area-axes",
    subcategory: "area-charts",
    subcategoryLabel: "Area Charts",
    name: "Area Axes",
    description: "An area chart with axes",
    exportName: "ChartAreaAxes",
  },
  {
    id: "chart-bar-interactive",
    subcategory: "bar-charts",
    subcategoryLabel: "Bar Charts",
    name: "Bar Interactive",
    description: "An interactive bar chart",
    exportName: "ChartBarInteractive",
  },
  {
    id: "chart-bar-default",
    subcategory: "bar-charts",
    subcategoryLabel: "Bar Charts",
    name: "Bar Default",
    description: "A bar chart",
    exportName: "ChartBarDefault",
  },
  {
    id: "chart-bar-horizontal",
    subcategory: "bar-charts",
    subcategoryLabel: "Bar Charts",
    name: "Bar Horizontal",
    description: "A horizontal bar chart",
    exportName: "ChartBarHorizontal",
  },
  {
    id: "chart-bar-multiple",
    subcategory: "bar-charts",
    subcategoryLabel: "Bar Charts",
    name: "Bar Multiple",
    description: "A multiple bar chart",
    exportName: "ChartBarMultiple",
  },
  {
    id: "chart-bar-stacked",
    subcategory: "bar-charts",
    subcategoryLabel: "Bar Charts",
    name: "Bar Stacked",
    description: "A stacked bar chart with a legend",
    exportName: "ChartBarStacked",
  },
  {
    id: "chart-bar-label",
    subcategory: "bar-charts",
    subcategoryLabel: "Bar Charts",
    name: "Bar Label",
    description: "A bar chart with a label",
    exportName: "ChartBarLabel",
  },
  {
    id: "chart-bar-label-custom",
    subcategory: "bar-charts",
    subcategoryLabel: "Bar Charts",
    name: "Bar Label Custom",
    description: "A bar chart with a custom label",
    exportName: "ChartBarLabelCustom",
  },
  {
    id: "chart-bar-mixed",
    subcategory: "bar-charts",
    subcategoryLabel: "Bar Charts",
    name: "Bar Mixed",
    description: "A mixed bar chart",
    exportName: "ChartBarMixed",
  },
  {
    id: "chart-bar-active",
    subcategory: "bar-charts",
    subcategoryLabel: "Bar Charts",
    name: "Bar Active",
    description: "A bar chart with an active bar",
    exportName: "ChartBarActive",
  },
  {
    id: "chart-bar-negative",
    subcategory: "bar-charts",
    subcategoryLabel: "Bar Charts",
    name: "Bar Negative",
    description: "A bar chart with negative values",
    exportName: "ChartBarNegative",
  },
  {
    id: "chart-line-interactive",
    subcategory: "line-charts",
    subcategoryLabel: "Line Charts",
    name: "Line Interactive",
    description: "An interactive line chart",
    exportName: "ChartLineInteractive",
  },
  {
    id: "chart-line-default",
    subcategory: "line-charts",
    subcategoryLabel: "Line Charts",
    name: "Line Default",
    description: "A line chart",
    exportName: "ChartLineDefault",
  },
  {
    id: "chart-line-linear",
    subcategory: "line-charts",
    subcategoryLabel: "Line Charts",
    name: "Line Linear",
    description: "A linear line chart",
    exportName: "ChartLineLinear",
  },
  {
    id: "chart-line-step",
    subcategory: "line-charts",
    subcategoryLabel: "Line Charts",
    name: "Line Step",
    description: "A line chart with step",
    exportName: "ChartLineStep",
  },
  {
    id: "chart-line-multiple",
    subcategory: "line-charts",
    subcategoryLabel: "Line Charts",
    name: "Line Multiple",
    description: "A multiple line chart",
    exportName: "ChartLineMultiple",
  },
  {
    id: "chart-line-dots",
    subcategory: "line-charts",
    subcategoryLabel: "Line Charts",
    name: "Line Dots",
    description: "A line chart with dots",
    exportName: "ChartLineDots",
  },
  {
    id: "chart-line-dots-custom",
    subcategory: "line-charts",
    subcategoryLabel: "Line Charts",
    name: "Line Dots Custom",
    description: "A line chart with custom dots",
    exportName: "ChartLineDotsCustom",
  },
  {
    id: "chart-line-dots-colors",
    subcategory: "line-charts",
    subcategoryLabel: "Line Charts",
    name: "Line Dots Colors",
    description: "A line chart with dots and colors",
    exportName: "ChartLineDotsColors",
  },
  {
    id: "chart-line-label",
    subcategory: "line-charts",
    subcategoryLabel: "Line Charts",
    name: "Line Label",
    description: "A line chart with a label",
    exportName: "ChartLineLabel",
  },
  {
    id: "chart-line-label-custom",
    subcategory: "line-charts",
    subcategoryLabel: "Line Charts",
    name: "Line Label Custom",
    description: "A line chart with a custom label",
    exportName: "ChartLineLabelCustom",
  },
  {
    id: "chart-pie-simple",
    subcategory: "pie-charts",
    subcategoryLabel: "Pie Charts",
    name: "Pie Simple",
    description: "A simple pie chart",
    exportName: "ChartPieSimple",
  },
  {
    id: "chart-pie-separator-none",
    subcategory: "pie-charts",
    subcategoryLabel: "Pie Charts",
    name: "Pie Separator None",
    description: "A pie chart with no separator",
    exportName: "ChartPieSeparatorNone",
  },
  {
    id: "chart-pie-label",
    subcategory: "pie-charts",
    subcategoryLabel: "Pie Charts",
    name: "Pie Label",
    description: "A pie chart with a label",
    exportName: "ChartPieLabel",
  },
  {
    id: "chart-pie-label-custom",
    subcategory: "pie-charts",
    subcategoryLabel: "Pie Charts",
    name: "Pie Label Custom",
    description: "A pie chart with a custom label",
    exportName: "ChartPieLabelCustom",
  },
  {
    id: "chart-pie-label-list",
    subcategory: "pie-charts",
    subcategoryLabel: "Pie Charts",
    name: "Pie Label List",
    description: "A pie chart with a label list",
    exportName: "ChartPieLabelList",
  },
  {
    id: "chart-pie-legend",
    subcategory: "pie-charts",
    subcategoryLabel: "Pie Charts",
    name: "Pie Legend",
    description: "A pie chart with a legend",
    exportName: "ChartPieLegend",
  },
  {
    id: "chart-pie-donut",
    subcategory: "pie-charts",
    subcategoryLabel: "Pie Charts",
    name: "Pie Donut",
    description: "A donut chart",
    exportName: "ChartPieDonut",
  },
  {
    id: "chart-pie-donut-active",
    subcategory: "pie-charts",
    subcategoryLabel: "Pie Charts",
    name: "Pie Donut Active",
    description: "A donut chart with an active sector",
    exportName: "ChartPieDonutActive",
  },
  {
    id: "chart-pie-donut-text",
    subcategory: "pie-charts",
    subcategoryLabel: "Pie Charts",
    name: "Pie Donut Text",
    description: "A donut chart with text",
    exportName: "ChartPieDonutText",
  },
  {
    id: "chart-pie-stacked",
    subcategory: "pie-charts",
    subcategoryLabel: "Pie Charts",
    name: "Pie Stacked",
    description: "A pie chart with stacked sections",
    exportName: "ChartPieStacked",
  },
  {
    id: "chart-pie-interactive",
    subcategory: "pie-charts",
    subcategoryLabel: "Pie Charts",
    name: "Pie Interactive",
    description: "An interactive pie chart",
    exportName: "ChartPieInteractive",
  },
  {
    id: "chart-radar-default",
    subcategory: "radar-charts",
    subcategoryLabel: "Radar Charts",
    name: "Radar Default",
    description: "A radar chart",
    exportName: "ChartRadarDefault",
  },
  {
    id: "chart-radar-dots",
    subcategory: "radar-charts",
    subcategoryLabel: "Radar Charts",
    name: "Radar Dots",
    description: "A radar chart with dots",
    exportName: "ChartRadarDots",
  },
  {
    id: "chart-radar-lines-only",
    subcategory: "radar-charts",
    subcategoryLabel: "Radar Charts",
    name: "Radar Lines Only",
    description: "A radar chart with lines only",
    exportName: "ChartRadarLinesOnly",
  },
  {
    id: "chart-radar-label-custom",
    subcategory: "radar-charts",
    subcategoryLabel: "Radar Charts",
    name: "Radar Label Custom",
    description: "A radar chart with a custom label",
    exportName: "ChartRadarLabelCustom",
  },
  {
    id: "chart-radar-grid-custom",
    subcategory: "radar-charts",
    subcategoryLabel: "Radar Charts",
    name: "Radar Grid Custom",
    description: "A radar chart with a custom grid",
    exportName: "ChartRadarGridCustom",
  },
  {
    id: "chart-radar-grid-none",
    subcategory: "radar-charts",
    subcategoryLabel: "Radar Charts",
    name: "Radar Grid None",
    description: "A radar chart with no grid",
    exportName: "ChartRadarGridNone",
  },
  {
    id: "chart-radar-grid-circle",
    subcategory: "radar-charts",
    subcategoryLabel: "Radar Charts",
    name: "Radar Grid Circle",
    description: "A radar chart with a grid and circle",
    exportName: "ChartRadarGridCircle",
  },
  {
    id: "chart-radar-grid-circle-no-lines",
    subcategory: "radar-charts",
    subcategoryLabel: "Radar Charts",
    name: "Radar Grid Circle No Lines",
    description: "A radar chart with a grid and circle fill",
    exportName: "ChartRadarGridCircleNoLines",
  },
  {
    id: "chart-radar-grid-circle-fill",
    subcategory: "radar-charts",
    subcategoryLabel: "Radar Charts",
    name: "Radar Grid Circle Fill",
    description: "A radar chart with a grid and circle fill",
    exportName: "ChartRadarGridCircleFill",
  },
  {
    id: "chart-radar-grid-fill",
    subcategory: "radar-charts",
    subcategoryLabel: "Radar Charts",
    name: "Radar Grid Fill",
    description: "A radar chart with a grid filled",
    exportName: "ChartRadarGridFill",
  },
  {
    id: "chart-radar-multiple",
    subcategory: "radar-charts",
    subcategoryLabel: "Radar Charts",
    name: "Radar Multiple",
    description: "A radar chart with multiple data",
    exportName: "ChartRadarMultiple",
  },
  {
    id: "chart-radar-legend",
    subcategory: "radar-charts",
    subcategoryLabel: "Radar Charts",
    name: "Radar Legend",
    description: "A radar chart with a legend",
    exportName: "ChartRadarLegend",
  },
  {
    id: "chart-radar-icons",
    subcategory: "radar-charts",
    subcategoryLabel: "Radar Charts",
    name: "Radar Icons",
    description: "A radar chart with icons",
    exportName: "ChartRadarIcons",
  },
  {
    id: "chart-radar-radius",
    subcategory: "radar-charts",
    subcategoryLabel: "Radar Charts",
    name: "Radar Radius",
    description: "A radar chart with a radius axis",
    exportName: "ChartRadarRadius",
  },
  {
    id: "chart-radial-simple",
    subcategory: "radial-charts",
    subcategoryLabel: "Radial Charts",
    name: "Radial Simple",
    description: "A radial chart",
    exportName: "ChartRadialSimple",
  },
  {
    id: "chart-radial-label",
    subcategory: "radial-charts",
    subcategoryLabel: "Radial Charts",
    name: "Radial Label",
    description: "A radial chart with a label",
    exportName: "ChartRadialLabel",
  },
  {
    id: "chart-radial-grid",
    subcategory: "radial-charts",
    subcategoryLabel: "Radial Charts",
    name: "Radial Grid",
    description: "A radial chart with a grid",
    exportName: "ChartRadialGrid",
  },
  {
    id: "chart-radial-text",
    subcategory: "radial-charts",
    subcategoryLabel: "Radial Charts",
    name: "Radial Text",
    description: "A radial chart with text",
    exportName: "ChartRadialText",
  },
  {
    id: "chart-radial-shape",
    subcategory: "radial-charts",
    subcategoryLabel: "Radial Charts",
    name: "Radial Shape",
    description: "A radial chart with a custom shape",
    exportName: "ChartRadialShape",
  },
  {
    id: "chart-radial-stacked",
    subcategory: "radial-charts",
    subcategoryLabel: "Radial Charts",
    name: "Radial Stacked",
    description: "A radial chart with stacked sections",
    exportName: "ChartRadialStacked",
  },
  {
    id: "chart-tooltip-default",
    subcategory: "tooltips",
    subcategoryLabel: "Tooltips",
    name: "Tooltip Default",
    description: "A stacked bar chart with a legend",
    exportName: "ChartTooltipDefault",
  },
  {
    id: "chart-tooltip-indicator-line",
    subcategory: "tooltips",
    subcategoryLabel: "Tooltips",
    name: "Tooltip Indicator Line",
    description: "A stacked bar chart with a legend",
    exportName: "ChartTooltipIndicatorLine",
  },
  {
    id: "chart-tooltip-indicator-none",
    subcategory: "tooltips",
    subcategoryLabel: "Tooltips",
    name: "Tooltip Indicator None",
    description: "A stacked bar chart with a legend",
    exportName: "ChartTooltipIndicatorNone",
  },
  {
    id: "chart-tooltip-label-custom",
    subcategory: "tooltips",
    subcategoryLabel: "Tooltips",
    name: "Tooltip Label Custom",
    description: "A stacked bar chart with a legend",
    exportName: "ChartTooltipLabelCustom",
  },
  {
    id: "chart-tooltip-label-formatter",
    subcategory: "tooltips",
    subcategoryLabel: "Tooltips",
    name: "Tooltip Label Formatter",
    description: "A stacked bar chart with a legend",
    exportName: "ChartTooltipLabelFormatter",
  },
  {
    id: "chart-tooltip-label-none",
    subcategory: "tooltips",
    subcategoryLabel: "Tooltips",
    name: "Tooltip Label None",
    description: "A stacked bar chart with a legend",
    exportName: "ChartTooltipLabelNone",
  },
  {
    id: "chart-tooltip-formatter",
    subcategory: "tooltips",
    subcategoryLabel: "Tooltips",
    name: "Tooltip Formatter",
    description: "A stacked bar chart with a legend",
    exportName: "ChartTooltipFormatter",
  },
  {
    id: "chart-tooltip-icons",
    subcategory: "tooltips",
    subcategoryLabel: "Tooltips",
    name: "Tooltip Icons",
    description: "A stacked bar chart with a legend",
    exportName: "ChartTooltipIcons",
  },
  {
    id: "chart-tooltip-advanced",
    subcategory: "tooltips",
    subcategoryLabel: "Tooltips",
    name: "Tooltip Advanced",
    description: "A stacked bar chart with a legend",
    exportName: "ChartTooltipAdvanced",
  },
];
