export interface MockBlock {
  blockUrl: string;
  description: string;
  id: string;
  name: string;
  previewUrl: string;
}

const slug = (name: string) => name.replace(/\s+/g, "-").toLowerCase();

const block = (name: string, opts?: { description?: string }): MockBlock => {
  const id = slug(name);
  return {
    id,
    name,
    description: opts?.description ?? `${name} blocks for your website.`,
    previewUrl: `/blocks/${id}`,
    blockUrl: `/blocks/${id}`,
  };
};

export const MOCK_BLOCKS: MockBlock[] = [
  block("Hero"),
  block("About"),
  block("Product List"),
  block("Product Detail"),
  block("Footer"),
  block("Feature"),
  block("Application Shell"),
  block("Navbar"),
  block("Integration"),
  block("Bento"),
  block("Pricing"),
  block("Blog"),
  block("Blog Post"),
  block("Gallery"),
  block("Download"),
  block("Projects"),
  block("Project"),
  block("Sidebar"),
  block("Team"),
  block("Timeline"),
  block("Shopping Cart"),
  block("Checkout"),
  block("Settings Profile"),
  block("Invite User"),
  block("Accept Invite"),
  block("Crud Companies"),
  block("Shader"),
  block("Field Mapping"),
  block("User Profile"),
  block("Contact"),
  block("Social Media Trending"),
  block("Help"),
  block("Product Card"),
  block("Ecommerce Hero"),
  block("Ecommerce Footer"),
  block("Ecommerce Navbar"),
  block("Product Quick View"),
  block("Address Book"),
  block("Awards"),
  block("Background Pattern"),
  block("Banner"),
  block("Book A Demo"),
  block("Careers"),
  block("Case Studies"),
  block("Case Study"),
  block("Changelog"),
  block("Chart Card"),
  block("Chart Group"),
  block("Code Example"),
  block("Community"),
  block("Compare"),
  block("Compare Products"),
  block("Compliance"),
  block("Content"),
  block("Cta"),
  block("Data Table"),
  block("Experience"),
  block("Faq"),
  block("Hero Feature Icons"),
  block("Incentives"),
  block("Industries"),
  block("Leaderboard"),
  block("List"),
  block("Live Purchase"),
  block("Login"),
  block("Logos"),
  block("Offer Modal"),
  block("Onboarding"),
  block("Order History"),
  block("Order Summary"),
  block("Payment Methods"),
  block("Process"),
  block("Product Categories"),
  block("Product Gallery"),
  block("Product Specs"),
  block("Promo Banner"),
  block("Rate Card"),
  block("Resource"),
  block("Resources"),
  block("Reviews"),
  block("Service"),
  block("Services"),
  block("Settings Integrations"),
  block("Settings Members"),
  block("Settings Notifications"),
  block("Signup"),
  block("Skills"),
  block("Stats"),
  block("Stats Card"),
  block("Testimonial"),
  block("Todo List"),
  block("Trust Strip"),
  block("Waitlist"),
  block("Wishlist"),
];
