// Generated by scripts/generate-framework-registry.mts (d6a4876939c7). Do not edit.
import { tv } from "tailwind-variants";

export const componentContract = {
  "description": "Checkbox composition backed by the Ark UI checkbox machine.",
  "name": "checkbox",
  "parts": [
    {
      "element": "div",
      "name": "CheckboxGroup",
      "slot": "checkbox-group"
    },
    {
      "element": "label",
      "name": "Checkbox",
      "primitive": "Checkbox.Root",
      "slot": "checkbox"
    },
    {
      "element": "div",
      "name": "CheckboxIndicator",
      "parent": "Checkbox",
      "primitive": "Checkbox.Indicator",
      "slot": "checkbox-indicator"
    }
  ],
  "props": {},
  "scenarios": [
    {
      "assertions": [
        "renders checked, unchecked and indeterminate indicators",
        "keeps the hidden input in the root"
      ],
      "name": "checked-state"
    },
    {
      "assertions": [
        "forwards invalid and disabled states",
        "emits the framework-native checked binding"
      ],
      "name": "form-state"
    }
  ],
  "strategy": "ark"
} as const;

export const checkboxVariants = tv({
  "base": [
    "relative",
    "inline-flex shrink-0 items-center justify-center",
    "size-4",
    "bg-transparent",
    "rounded-sm border border-input shadow-xs/5",
    "transition-shadow",
    "data-focus-visible:border-primary data-focus-visible:ring-[3px] data-focus-visible:ring-ring/32 data-focus-visible:ring-offset-1 data-focus-visible:ring-offset-background",
    "dark:data-focus-visible:data-invalid:border-destructive-foreground/64 dark:data-focus-visible:data-invalid:ring-destructive-foreground/48",
    "data-disabled:opacity-64",
    "[[data-disabled],[data-checked],[data-invalid]]:shadow-none",
    "data-invalid:border-destructive data-invalid:ring-[3px] data-invalid:ring-destructive/24",
    "dark:data-invalid:border-destructive-foreground dark:data-invalid:text-destructive-foreground dark:data-invalid:ring-destructive-foreground/20",
    "dark:not-data-checked:bg-input/32 dark:data-invalid:ring-destructive-foreground/24",
    "motion-reduce:transition-none!"
  ]
});
