// Generated by scripts/generate-framework-registry.mts (ac9da05fa6ce). Do not edit.
import { tv } from "tailwind-variants";

export const componentContract = {
  "description": "Accessible modal and non-modal dialog composition.",
  "name": "dialog",
  "parts": [
    {
      "name": "Dialog",
      "primitive": "Dialog.Root",
      "slot": "dialog-root"
    },
    {
      "element": "button",
      "name": "DialogTrigger",
      "parent": "Dialog",
      "primitive": "Dialog.Trigger",
      "slot": "dialog-trigger"
    },
    {
      "element": "div",
      "name": "DialogOverlay",
      "parent": "Dialog",
      "primitive": "Dialog.Backdrop",
      "slot": "dialog-overlay"
    },
    {
      "element": "div",
      "name": "DialogPositioner",
      "parent": "Dialog",
      "primitive": "Dialog.Positioner",
      "slot": "dialog-positioner"
    },
    {
      "element": "div",
      "name": "DialogContent",
      "parent": "DialogPositioner",
      "primitive": "Dialog.Content",
      "slot": "dialog-content"
    },
    {
      "element": "div",
      "name": "DialogBody",
      "parent": "DialogContent",
      "slot": "dialog-body"
    },
    {
      "element": "div",
      "name": "DialogHeader",
      "parent": "DialogContent",
      "slot": "dialog-header"
    },
    {
      "element": "h2",
      "name": "DialogTitle",
      "parent": "DialogHeader",
      "primitive": "Dialog.Title",
      "slot": "dialog-title"
    },
    {
      "element": "div",
      "name": "DialogDescription",
      "parent": "DialogHeader",
      "primitive": "Dialog.Description",
      "slot": "dialog-description"
    },
    {
      "element": "button",
      "name": "DialogClose",
      "parent": "DialogContent",
      "primitive": "Dialog.CloseTrigger",
      "slot": "dialog-close-trigger"
    },
    {
      "element": "div",
      "name": "DialogFooter",
      "parent": "DialogContent",
      "slot": "dialog-footer"
    }
  ],
  "props": {
    "bottomStickOnMobile": {
      "defaultValue": true,
      "description": "Dock content to the viewport bottom on small screens.",
      "type": "boolean"
    },
    "lazyMount": {
      "defaultValue": true,
      "description": "Mount dialog content on first open.",
      "type": "boolean"
    },
    "modal": {
      "defaultValue": true,
      "description": "Enable modal focus and pointer behavior.",
      "type": "boolean"
    },
    "scrollFade": {
      "defaultValue": false,
      "description": "Add a fade treatment to overflowing body content.",
      "type": "boolean"
    },
    "showCloseButton": {
      "defaultValue": true,
      "description": "Render the icon close action.",
      "type": "boolean"
    },
    "size": {
      "defaultValue": "md",
      "description": "Set the maximum content width.",
      "type": "DialogSize",
      "values": [
        "sm",
        "md",
        "lg",
        "xl",
        "2xl",
        "3xl",
        "4xl",
        "5xl",
        "6xl",
        "fullscreen"
      ]
    },
    "unmountOnExit": {
      "defaultValue": true,
      "description": "Remove dialog content after the exit transition.",
      "type": "boolean"
    }
  },
  "scenarios": [
    {
      "assertions": [
        "defaults modal, lazyMount and unmountOnExit to true",
        "supports controlled and uncontrolled open state"
      ],
      "name": "root-state"
    },
    {
      "assertions": [
        "omits the backdrop when modal is false",
        "portals content",
        "exposes an accessible title"
      ],
      "name": "composition"
    },
    {
      "assertions": [
        "renders every size",
        "shows the close action by default",
        "supports mobile bottom docking"
      ],
      "name": "content"
    }
  ],
  "strategy": "ark"
} as const;

export const dialogOverlayVariants = tv({
  "base": [
    "fixed inset-0 z-50",
    "bg-black/32 backdrop-blur-xs",
    "duration-200",
    "peer peer-data-[slot=dialog-overlay]:hidden",
    "data-[state=open]:fade-in-0 data-[state=open]:animate-in",
    "data-[state=closed]:fade-out-0 data-[state=closed]:animate-out",
    "motion-reduce:animate-none!"
  ]
});

export const dialogContentVariants = tv({
  "base": [
    "[--space:--spacing(6)]",
    "z-[calc(50+var(--layer-index,0))]",
    "relative",
    "row-start-2",
    "max-h-[calc(100svh-2rem)] min-h-0 w-full min-w-0",
    "flex flex-col overflow-hidden",
    "bg-popover",
    "text-popover-foreground",
    "rounded-2xl border shadow-lg/5",
    "outline-none",
    "translate-y-[calc(-1.25rem*var(--nested-layer-count))]",
    "transition-[scale,opacity,translate] duration-200 ease-in-out will-change-transform",
    "data-[nested=dialog]:data-[state=closed]:slide-in-from-bottom-10 data-[nested=dialog]:data-[state=open]:slide-in-from-bottom-10 data-[has-nested=dialog]:origin-top",
    "scale-[calc(1-0.1*var(--nested-layer-count))] opacity-[calc(1-0.1*var(--nested-layer-count))]",
    "data-[state=closed]:fade-out-0 data-[state=closed]:zoom-out-[98%] data-[state=closed]:animate-out",
    "data-[state=open]:fade-in-0 data-[state=open]:zoom-in-[98%] data-[state=open]:animate-in",
    "motion-reduce:animate-none! motion-reduce:transition-none!"
  ],
  "defaultVariants": {
    "bottomStickOnMobile": true,
    "size": "md"
  },
  "variants": {
    "bottomStickOnMobile": {
      "false": null,
      "true": [
        "max-sm:max-h-[calc(100svh-3rem)]",
        "max-sm:max-w-none",
        "max-sm:rounded-none max-sm:rounded-t-2xl max-sm:border-x-0 max-sm:border-t max-sm:border-b-0",
        "max-sm:opacity-[calc(1-min(var(--nested-dialogs),1))]",
        "max-sm:data-[state=closed]:slide-out-to-bottom-5 max-sm:data-[state=open]:slide-in-from-bottom-5",
        "max-sm:data-[state=closed]:zoom-out-100 max-sm:data-[state=open]:zoom-in-100"
      ]
    },
    "size": {
      "2xl": "max-w-3xl",
      "3xl": "max-w-4xl",
      "4xl": "max-w-5xl",
      "5xl": "max-w-6xl",
      "6xl": "max-w-7xl",
      "fullscreen": "size-full",
      "lg": "max-w-xl",
      "md": "max-w-lg",
      "sm": "max-w-md",
      "xl": "max-w-2xl"
    }
  }
});
