import { defineRegistryComponent } from "./schema";

const sidebarParts = [
  ["SidebarProvider", "sidebar-wrapper", "div"],
  ["Sidebar", "sidebar", "aside"],
  ["SidebarTrigger", "sidebar-trigger", "button"],
  ["SidebarRail", "sidebar-rail", "button"],
  ["SidebarInset", "sidebar-inset", "main"],
  ["SidebarInput", "sidebar-input", "input"],
  ["SidebarHeader", "sidebar-header", "div"],
  ["SidebarFooter", "sidebar-footer", "div"],
  ["SidebarSeparator", "sidebar-separator", "div"],
  ["SidebarContent", "sidebar-content", "div"],
  ["SidebarGroup", "sidebar-group", "div"],
  ["SidebarGroupLabel", "sidebar-group-label", "div"],
  ["SidebarGroupAction", "sidebar-group-action", "button"],
  ["SidebarGroupContent", "sidebar-group-content", "div"],
  ["SidebarMenu", "sidebar-menu", "ul"],
  ["SidebarMenuItem", "sidebar-menu-item", "li"],
  ["SidebarMenuButton", "sidebar-menu-button", "button"],
  ["SidebarMenuAction", "sidebar-menu-action", "button"],
  ["SidebarMenuBadge", "sidebar-menu-badge", "div"],
  ["SidebarMenuSkeleton", "sidebar-menu-skeleton", "div"],
  ["SidebarMenuSub", "sidebar-menu-sub", "ul"],
  ["SidebarMenuSubItem", "sidebar-menu-sub-item", "li"],
  ["SidebarMenuSubButton", "sidebar-menu-sub-button", "a"],
] as const;

const sidebarDefinition = defineRegistryComponent({
  adapters: {
    react: {
      bindings: { open: "open", openChange: "onOpenChange" },
      evidence: {
        composition: ["placement", "inset-s-0", "inset-e-0"],
        "desktop-state": ["sidebar_state", "useHotkey", "mod+"],
        "mobile-state": ["isMobile", "openMobile"],
      },
      packageVersion: "5.39.1",
      sources: ["sidebar.tsx"],
      status: "stable",
    },
    solid: {
      bindings: { open: "open", openChange: "onOpenChange" },
      evidence: {
        composition: ["placement", "inset-s-0", "inset-e-0"],
        "desktop-state": ["sidebar_state", "matchMedia", "metaKey"],
        "mobile-state": ["isMobile", "openMobile"],
      },
      packageVersion: "5.39.1",
      sources: ["sidebar.tsx"],
      status: "preview",
    },
    svelte: {
      bindings: { open: "open", openChange: "onOpenChange" },
      evidence: {
        composition: ["placement", "inset-s-0", "inset-e-0"],
        "desktop-state": ["sidebar_state", "matchMedia", "metaKey"],
        "mobile-state": ["isMobile", "openMobile"],
      },
      packageVersion: "5.24.1",
      sources: [
        "sidebar/index.ts",
        "sidebar/sidebar-content.svelte",
        "sidebar/sidebar-context.ts",
        "sidebar/sidebar-footer.svelte",
        "sidebar/sidebar-group-action.svelte",
        "sidebar/sidebar-group-content.svelte",
        "sidebar/sidebar-group-label.svelte",
        "sidebar/sidebar-group.svelte",
        "sidebar/sidebar-header.svelte",
        "sidebar/sidebar-input.svelte",
        "sidebar/sidebar-inset.svelte",
        "sidebar/sidebar-menu-action.svelte",
        "sidebar/sidebar-menu-badge.svelte",
        "sidebar/sidebar-menu-button.svelte",
        "sidebar/sidebar-menu-item.svelte",
        "sidebar/sidebar-menu-skeleton.svelte",
        "sidebar/sidebar-menu-sub-button.svelte",
        "sidebar/sidebar-menu-sub-item.svelte",
        "sidebar/sidebar-menu-sub.svelte",
        "sidebar/sidebar-menu.svelte",
        "sidebar/sidebar-part.svelte",
        "sidebar/sidebar-provider.svelte",
        "sidebar/sidebar-rail.svelte",
        "sidebar/sidebar-separator.svelte",
        "sidebar/sidebar-trigger.svelte",
        "sidebar/sidebar.svelte",
      ],
      status: "preview",
    },
    vue: {
      bindings: { open: "open", openChange: "update:open" },
      evidence: {
        composition: ["placement", "inset-s-0", "inset-e-0"],
        "desktop-state": ["sidebar_state", "matchMedia", "metaKey"],
        "mobile-state": ["isMobile", "openMobile"],
      },
      packageVersion: "5.39.1",
      sources: ["sidebar/index.ts", "sidebar/sidebar.ts"],
      status: "preview",
    },
  },
  dependencies: {
    common: ["tailwind-variants"],
    frameworks: {
      react: ["@ark-ui/react", "lucide-react"],
      solid: ["@ark-ui/solid", "solid-js"],
      svelte: ["@ark-ui/svelte", "svelte"],
      vue: ["@ark-ui/vue", "vue"],
    },
    registry: {
      react: [
        "button",
        "hotkeys",
        "input",
        "scroll-area",
        "separator",
        "sheet",
        "skeleton",
        "tooltip",
        "use-is-mobile",
      ],
      solid: ["button"],
      svelte: ["button"],
      vue: ["button"],
    },
  },
  description: "Responsive application sidebar with controlled collapse state.",
  name: "sidebar",
  parts: sidebarParts.map(([name, slot, element]) => ({ element, name, slot })),
  props: {
    collapsible: {
      defaultValue: "offcanvas",
      description: "Choose how the desktop sidebar collapses.",
      type: "SidebarCollapsible",
      values: ["offcanvas", "icon", "none"],
    },
    defaultOpen: {
      defaultValue: true,
      description: "Set the initial uncontrolled desktop state.",
      type: "boolean",
    },
    isActive: {
      defaultValue: false,
      description: "Mark a menu action as the current destination.",
      type: "boolean",
    },
    placement: {
      defaultValue: "left",
      description: "Place the sidebar at the logical start or end.",
      type: "SidebarPlacement",
      values: ["left", "right"],
    },
    scrollFade: {
      defaultValue: false,
      description: "Add a fade treatment to overflowing navigation.",
      type: "boolean",
    },
    showIcon: {
      defaultValue: false,
      description: "Render an icon placeholder in menu skeletons.",
      type: "boolean",
    },
    showOnHover: {
      defaultValue: false,
      description: "Keep a menu action visible only around interaction.",
      type: "boolean",
    },
    variant: {
      defaultValue: "sidebar",
      description: "Select the shell treatment.",
      type: "SidebarVariant",
      values: ["sidebar", "floating", "inset"],
    },
  },
  recipes: [],
  scenarios: [
    {
      assertions: [
        "supports controlled and uncontrolled desktop state",
        "persists desktop state for seven days",
        "toggles with mod+b",
      ],
      name: "desktop-state",
    },
    {
      assertions: [
        "uses an independent mobile open state",
        "closes the mobile surface through its binding",
      ],
      name: "mobile-state",
    },
    {
      assertions: [
        "preserves every public part and data-slot",
        "supports left and right placement",
        "keeps logical RTL layout classes",
      ],
      name: "composition",
    },
  ],
  strategy: "custom",
});

export default sidebarDefinition;
