import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import {
  FRAMEWORKS,
  type RegistryComponentDefinition,
  type RegistryFramework,
  registryDefinitions,
} from "../registry/definitions";

const CWD = process.cwd();
const CHECK_ONLY = process.argv.includes("--check");
const REPORT_PATH = join(CWD, "registry", "framework-parity.json");

const serialize = (value: unknown) => JSON.stringify(value, null, 2);
const markdownCell = (value: unknown) =>
  value === undefined ? "—" : `\`${String(value).replaceAll("|", "\\|")}\``;

const renderContractModule = (definition: RegistryComponentDefinition) => {
  const canonical = serialize({
    description: definition.description,
    name: definition.name,
    parts: definition.parts,
    props: definition.props,
    scenarios: definition.scenarios,
    strategy: definition.strategy,
  });
  const digest = createHash("sha256")
    .update(serialize(definition))
    .digest("hex")
    .slice(0, 12);
  const recipes = definition.recipes
    .map(
      (recipe) =>
        `export const ${recipe.name} = tv(${serialize({
          base: recipe.base,
          ...(recipe.defaultVariants
            ? { defaultVariants: recipe.defaultVariants }
            : {}),
          ...(recipe.variants ? { variants: recipe.variants } : {}),
        })});`
    )
    .join("\n\n");

  return `// Generated by scripts/generate-framework-registry.mts (${digest}). Do not edit.\nimport { tv } from "tailwind-variants";\n\nexport const componentContract = ${canonical} as const;\n\n${recipes}\n`;
};

const renderContractDocs = (definition: RegistryComponentDefinition) => {
  const anatomy = definition.parts
    .map(
      ({ name, parent, primitive, slot }) =>
        `| ${markdownCell(name)} | ${markdownCell(parent)} | ${markdownCell(primitive)} | ${markdownCell(slot)} |`
    )
    .join("\n");
  const props = Object.entries(definition.props)
    .map(
      ([name, prop]) =>
        `| ${markdownCell(name)} | ${markdownCell(prop.type)} | ${markdownCell(prop.defaultValue)} | ${prop.description} |`
    )
    .join("\n");
  const variants = definition.recipes.flatMap((recipe) =>
    Object.entries(recipe.variants ?? {}).map(
      ([name, values]) =>
        `| ${markdownCell(recipe.name)} | ${markdownCell(name)} | ${markdownCell(Object.keys(values).join(", "))} | ${markdownCell(recipe.defaultVariants?.[name])} |`
    )
  );

  return `{/* Generated by scripts/generate-framework-registry.mts. Do not edit. */}

## Anatomy

| Export | Parent | Primitive | data-slot |
| --- | --- | --- | --- |
${anatomy}

## Shark props

| Prop | Type | Default | Description |
| --- | --- | --- | --- |
${props || "| — | — | — | No Shark-specific props. |"}

## Variants

| Recipe | Axis | Values | Default |
| --- | --- | --- | --- |
${variants.join("\n") || "| — | — | — | — |"}
`;
};

const readOrEmpty = async (path: string) => {
  try {
    return await readFile(path, "utf8");
  } catch {
    return "";
  }
};

const writeGenerated = async (path: string, content: string) => {
  const current = await readOrEmpty(path);
  if (current === content) {
    return false;
  }
  if (CHECK_ONLY) {
    throw new Error(
      `[framework registry] stale generated file: ${path.replace(`${CWD}/`, "")}`
    );
  }
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, content);
  return true;
};

interface AdapterReport {
  bindings: Record<string, string>;
  missingEvidence: string[];
  missingParts: string[];
  missingProps: string[];
  missingRecipes: string[];
  missingSlots: string[];
  missingSources: string[];
  packageVersion: string;
  status: string;
}

const inspectAdapter = async (
  definition: RegistryComponentDefinition,
  framework: RegistryFramework
): Promise<AdapterReport> => {
  const adapter = definition.adapters[framework];
  const root = join(CWD, "registry", framework, "components");
  const entries = await Promise.all(
    adapter.sources.map(async (source) => ({
      content: await readOrEmpty(join(root, source)),
      source,
    }))
  );
  const combinedSource = entries.map(({ content }) => content).join("\n");

  return {
    bindings: adapter.bindings,
    missingEvidence:
      adapter.status === "unsupported"
        ? []
        : Object.entries(adapter.evidence).flatMap(([scenario, tokens]) =>
            tokens
              .filter((token) => !combinedSource.includes(token))
              .map((token) => `${scenario}:${token}`)
          ),
    missingParts:
      adapter.status === "unsupported"
        ? definition.parts.map(({ name }) => name)
        : definition.parts
            .filter(({ name }) => !combinedSource.includes(name))
            .map(({ name }) => name),
    missingProps:
      adapter.status === "unsupported"
        ? []
        : Object.keys(definition.props).filter(
            (prop) => !combinedSource.includes(prop)
          ),
    missingRecipes:
      adapter.status === "unsupported"
        ? []
        : definition.recipes
            .filter(({ name }) => !combinedSource.includes(name))
            .map(({ name }) => name),
    missingSlots:
      adapter.status === "unsupported"
        ? definition.parts
            .filter(({ element }) => element)
            .map(({ slot }) => slot)
        : definition.parts
            .filter(
              ({ element, slot }) => element && !combinedSource.includes(slot)
            )
            .map(({ slot }) => slot),
    missingSources: entries
      .filter(({ content }) => content.length === 0)
      .map(({ source }) => source),
    packageVersion: adapter.packageVersion,
    status: adapter.status,
  };
};

const main = async () => {
  const report: Record<string, Record<string, AdapterReport>> = {};
  let generatedCount = 0;

  const adapters = await Promise.all(
    registryDefinitions.flatMap((definition) =>
      FRAMEWORKS.map(async (framework) => {
        const contractPath = join(
          CWD,
          "registry",
          framework,
          "components",
          "_shark",
          `${definition.name}.contract.ts`
        );
        const [generated, adapterReport] = await Promise.all([
          writeGenerated(contractPath, renderContractModule(definition)),
          inspectAdapter(definition, framework),
        ]);
        return { adapterReport, definition, framework, generated };
      })
    )
  );

  for (const { adapterReport, definition, framework, generated } of adapters) {
    report[definition.name] ??= {};
    report[definition.name][framework] = adapterReport;
    generatedCount += Number(generated);
  }

  const generatedDocs = await Promise.all(
    registryDefinitions.map((definition) =>
      writeGenerated(
        join(CWD, "registry", "generated-docs", `${definition.name}.mdx`),
        renderContractDocs(definition)
      )
    )
  );
  generatedCount += generatedDocs.filter(Boolean).length;

  const reportContent = `${serialize({
    components: report,
    frameworks: FRAMEWORKS,
    schemaVersion: 1,
  })}\n`;
  if (await writeGenerated(REPORT_PATH, reportContent)) {
    generatedCount += 1;
  }

  const blocking = Object.entries(report).flatMap(([component, frameworks]) =>
    Object.entries(frameworks).flatMap(([framework, adapter]) => {
      if (adapter.status === "unsupported") {
        return [];
      }
      const details = [
        ...adapter.missingSources.map((source) => `source:${source}`),
        ...adapter.missingParts.map((part) => `part:${part}`),
        ...adapter.missingProps.map((prop) => `prop:${prop}`),
        ...adapter.missingRecipes.map((recipe) => `recipe:${recipe}`),
        ...adapter.missingSlots.map((slot) => `slot:${slot}`),
        ...adapter.missingEvidence.map((evidence) => `evidence:${evidence}`),
      ];
      return details.length > 0
        ? [`${component}.${framework} -> ${details.join(", ")}`]
        : [];
    })
  );

  if (blocking.length > 0) {
    throw new Error(
      `[framework registry] adapter parity failed:\n${blocking
        .map((failure) => `- ${failure}`)
        .join("\n")}`
    );
  }

  console.log(
    CHECK_ONLY
      ? `Framework registry is synchronized (${registryDefinitions.length} definitions).`
      : `Generated ${generatedCount} framework registry artifacts.`
  );
};

await main();
